spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/orderinfomation?characterEncoding=utf-8&useSSL=false
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
eureka:
  client:
    service-url:
      defaultZone: http://${eurekaUserName}:${eurekaPassWord}@peer1:2021/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

eurekaUserName: lian
eurekaPassWord: lian

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl