spring:
  application:
    name: product-mucon
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: king
    password: 123456
    url: jdbc:mysql://101.201.101.138:10001/product?characterEncoding=utf-8&useSSL=false
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

eureka:
  client:
    service-url:
      defaultZone: http://${eurekaUserName}:${eurekaPassWord}@peer1:2021/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.jkzn.productmucon.productmucon.domain



eurekaUserName: lian
eurekaPassWord: lian